lib/build.ml, lib/build.mli, lib/config.ml, lib/obuilder.ml, lib/os.ml, lib/runc_sandbox.ml, lib/s.ml, main.ml, test/mock_sandbox.ml, test/mock_sandbox.mli, test/test.ml
When a command run by `runc` fails, report the error as coming from that command, not from `runc`.
=> Improve error reporting

lib/btrfs_store.ml, lib/build.ml, lib/build.mli, lib/build_log.ml, lib/build_log.mli, lib/db_store.ml, lib/db_store.mli, lib/obuilder.ml, lib/os.ml, lib/runc_sandbox.ml, lib/s.ml, lib/zfs_store.ml, main.ml, test/dune, test/mock_sandbox.ml, test/mock_sandbox.mli, test/mock_store.ml, test/test.ml
This also simplifies the logic for the individual store backends, by moving log handling to the `Db_store` wrapper.
=> Combine parallel builds for the same key

lib/build.ml, lib/build_log.ml, lib/db_store.ml
1. Ignore requests to close the `empty` singleton log.
2. Ensure we finishing tailing the log before continuing.
=> Fix some logging bugs

README.md, lib/db_store.ml, test/test.ml
Also, only log messages about cancellations if the build isn't already finished, as it's common to turn off the switch after a successful build.
=> Add some notes to the documentation

lib/db_store.ml, test/test.ml
1. A build fails.
2. A new build is started for the same id.
3. The original build is cancelled.
4. The new build is removed from `in_progress`.
=> Avoid possible race when cancelling

lib/db_store.ml, test/log.ml, test/mock_store.ml, test/test.ml
Store backends shouldn't have to deal with being asked to build the same thing twice concurrently.
=> Wait for a cancelling build to finish before starting replacement

Makefile, README.md, lib/btrfs_store.ml, lib/s.ml, lib/zfs_store.ml, stress/stress.ml
Should cope better with crash recovery now.
=> Document and improve zfs lifecycle

README.md, lib/btrfs_store.ml, lib/build.ml, lib/db_store.mli, lib/escape.ml, lib/obuilder.ml, lib/s.ml, lib/zfs_store.ml, lib_spec/cache.ml, lib_spec/cache.mli, lib_spec/docker.ml, lib_spec/docker.mli, lib_spec/obuilder_spec.ml, lib_spec/spec.ml, lib_spec/spec.mli, main.ml, stress/stress.ml, test/test.ml
Also, remove cache naming restrictions.
Instead, have the backends escape the name as necessary if they need to.
=> Add Docker BuildKit-format conversion

.run-travis-tests.sh, lib/btrfs_store.ml, lib/build.ml, lib/os.ml, lib/tar_transfer.ml, lib/tar_transfer.mli, lib/zfs_store.ml, test/mock_exec.ml
Use ustar tar format for copying files, raising the limit from 100 bytes to at least 155 bytes and (depending on the path) up to 256 bytes.
ocaml-tar also allows you to select the `Posix` level, which should allow unlimited file lengths. However, this appears to be unimplemented for archive creation.
=> Support copying paths with longer names

README.md, example.spec, lib/build.ml, lib/config.ml, lib/runc_sandbox.ml, lib_spec/docker.ml, lib_spec/spec.ml, lib_spec/spec.mli
For now, the only options are `(network host)` (uncontained, as before) and nothing (isolated private network; the new default).
=> Add syntax for configuring networks

lib/runc_sandbox.ml
- Document Linux capabilities
- Only share host resolv.conf if container uses host networking
- Remove CAP_NET_RAW and CAP_NET_BIND_SERVICE
- Make runc mounts configuration more like Docker's configuration
- Remove rootless runc options
=> Tighten runc policy slightly

lib/build.ml, lib/tar_transfer.ml, lib/tar_transfer.mli
We should only treat `dst` as a directory if it ends with `/`. We only applied this rule for directories, but it should also apply to files and symlinks.
=> Fix copying of a single file to a directory

lib/runc_sandbox.ml
Duniverse builds need this, for example, to cache `_build`.
=> Remove noexec from cache mounts

lib/btrfs_store.ml
Might help with problems such as this:
```
[11030132.006555] INFO: task ocluster-worker:602217 blocked for more than 120 seconds.
[11030132.015596]       Not tainted 5.4.0-40-generic #44-Ubuntu
[11030132.022547] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[11030132.032061] ocluster-worker D    0 602217      1 0x00004000
[11030132.032069] Call Trace:
[11030132.032092]  __schedule+0x2e3/0x740
[11030132.032106]  ? __switch_to_asm+0x40/0x70
[11030132.032116]  ? __switch_to_asm+0x34/0x70
[11030132.032126]  schedule+0x42/0xb0
[11030132.032130]  schedule_preempt_disabled+0xe/0x10
[11030132.032132]  __mutex_lock.isra.0+0x182/0x4f0
[11030132.032142]  ? try_to_del_timer_sync+0x54/0x80
[11030132.032145]  __mutex_lock_slowpath+0x13/0x20
[11030132.032148] …
```
=> Use mutex to avoid concurrent btrfs operations

.run-travis-tests.sh, README.md, lib/runc_sandbox.ml, lib/runc_sandbox.mli, main.ml, stress/stress.ml
Sync operations are really slow on btrfs. They're also pointless, since if the computer crashes while we're doing a build then we'll just throw it away and start again anyway.
This commit provides a seccomp policy that causes all sync operations to "fail", with errno 0 ("success").
On my machine, this reduces the time to `apt-get install -y shared-mime-info` from 18.5s to 4.7s.
Based on https://bblank.thinkmo.de/using-seccomp-to-filter-sync-operations.html
=> Use seccomp policy to avoid necessary sync operations

lib/build.ml, lib_spec/spec.ml, lib_spec/spec.mli, test/test.ml
Before:
```sexp
((from
ocaml/opam@sha256:b2245cea39ed16fd39bd7ab70204b28fb73d1364e1bc702ef495798349e55e4f)
(comment debian-10-4.10) (user (uid 1000) (gid 1000))
(run (cache (opam-archives (target /home/opam/.opam/download-cache)))
(network host) (shell "opam install dune.2.7.1"))
(run (cache (opam-archives (target /home/opam/.opam/download-cache)))
(network host)
(shell
"opam pin add -n https://github.com/ocamllabs/duniverse.git#6b6c1b8173afab88933762f6b5ee82a070b2d715"))
(run (cache (opam-archives (target /home/opam/.opam/download-cache)))
(network host) (shell "opam depext --update -y opam-monorepo"))
(run (cache (opam-archives (target /home/opam/.opam/download-cache)))
(network host) (shell "opam install opam-monorepo"))
(workdir /src) (run (shell "sudo chown opam /src"))
(copy (src …
```
=> Improve formatting of OBuilder specs

lib/build.ml, lib/os.ml, lib/runc_sandbox.ml, lib_spec/spec.ml, test/mock_exec.ml
Also, clean up handling of redirections when spawning subprocesses (/cc @patricoferris).
=> Record log output from docker pull 

lib/s.ml, lib_spec/docker.mli, lib_spec/spec.ml, lib_spec/spec.mli, main.ml, stress/stress.ml, test/test.ml
The idea was that a spec would be a list of stages, as in a Dockerfile, but it probably makes more sense to allow nested builds instead.
=> Rename `stage` type to `t`

dune-project, lib_spec/docker.ml, lib_spec/docker.mli, lib_spec/dune, main.ml, obuilder-spec.opam, test/test.ml
This causes some vendoring difficulties with the CI, which depends on dockerfile via dockerfile-opam and also via obuilder, and it's only a few lines longer this way.
It also allows us more control over the formatting (e.g. putting a blank line between stages in multi-stage builds).
=> Remove dependency on dockerfile

.run-travis-tests.sh, README.md, lib/build.ml, lib/obuilder.ml, lib/os.ml, lib/s.ml, main.ml
This runs `docker version` to check that Docker is installed and working, and does a test build (running `echo` in a `busybox` container).
=> Add a healthcheck feature

lib/runc_sandbox.ml, lib/runc_sandbox.mli, main.ml, stress/stress.ml
If btrfs crashes and makes the FS read-only then after rebooting there will be stale runc directories. New jobs with the same IDs will then fail.
=> Clean up left-over runc containers on restart

lib/build.ml
In testing, a moderately busy 48-core machine with a load of 27 took longer than 10s.
=> Increase healthcheck timeout

CHANGES.md, README.md, lib/build.ml, lib/build.mli, lib/config.ml, lib/runc_sandbox.ml, lib_spec/docker.ml, lib_spec/obuilder_spec.ml, lib_spec/secret.ml, lib_spec/secret.mli, lib_spec/spec.ml, lib_spec/spec.mli, main.ml, test/test.ml
A secret is an externally provided key-value pair that can be mounted on demand by the job. This PR implements:
- Spec: adding a `secrets` field in the `run` command, which mounts a list of secrets files in the chosen target, or in `/run/secrets/[id]` if the target is not provided. 
- Spec: when translated to docker, the secret list translate's to buildkit's `--mount=type=secret,id=[id],dst=[target]` option. 
- Obuilder: a temporary file and a mount point are created for each specified secret. Obuilder's build context has an additional `secrets` parameter in order to provide the values.
=> Add support for secrets

.run-travis-tests.sh, lib/btrfs_store.ml
=> btrfs: Check that the current kernel version will not have issues down the line

lib/runc_sandbox.ml
It got turned into a bool in 8225864a6e3daa (so you had to do `--fast-sync=true`), I assume by accident.
/cc @patricoferris
=> Convert --fast-sync back to a flag

dune, main.ml
The first commit is just a switch to `Cmdliner.Arg.&`, I find it cleaner and it's more in line with Cmdliner's documentation, but I can remove it if you prefer. (EDIT: removed).
The second introduces support for Fmt.cli, that's the `--color=always|never|auto` flag, and support for setting logs verbosity through the command line. This introduces a bit of noise in the help page, but helps development by not having to patch the source to get more logs. The new options are only available through sub-commands.
One thing: in `setup_log`, maybe setting both
```ocaml
Logs.set_level level;
Logs.Src.set_level Obuilder.log_src level;
```
is redundant, I'm not sure.
=> Support Fmt.cli and Logs.cli

.gitignore, lib/build.ml, lib/dao.ml, lib/docker.ml, lib/manifest.ml, lib/os.ml, lib/runc_sandbox.ml, lib/runc_sandbox.mli, lib/s.ml, lib/tar_transfer.ml, main.ml
Some easy bits cherry-picked from #75:
- Remove trailing whitespace.
- Don't try to use `sudo` on non-Unix platforms.
- Add `_opam` to `.gitignore`.
=> Some minor changes from the Docker branch

.github/workflows/main.yml
This PR fixes #89 for CI.
@talex5 wasn't quite sure what you wanted when you said 
> And maybe link to the issue from the error message?
=> Fix ZFS tests in CI

lib_spec/docker.ml, test/test.ml
See this for more explanations.
https://github.com/avsm/ocaml-dockerfile/pull/53#issuecomment-863216230
=> Properly escape ENV variables in generated Dockerfiles

lib/runc_sandbox.ml
During start up `clean_runc` attempts to delete any left over `runc` containers, but if these containers are still running the delete operation fails and `ocluster-worker` crashes.  Adding the `--force` parameter will send a SIGKILL to the container before attempting to delete it.
=> Added --force parameter to runc delete

.github/workflows/main.yml, .run-gha-tests.sh
The download cache is probably a drop in the ocean compared to downloading opam packages.
=> Update runc to 1.1.0 and cache its download

dune-project, lib/build.mli, lib/db_store.ml, obuilder-spec.opam, obuilder.opam, stress/dune, test/mock_sandbox.ml, test/mock_sandbox.mli, test/test.ml
Bumping to Dune 3.3 enables warnings 67 (unused functor parameter) and 69 (record field is never read), which I tried fixing.
If only the `obuilder-spec` package is build, then Dune tries to build the `stress.exe` executable which requires the `obuidler` library. Use a workaround to attach `stress.exe` to the `obuilder` package.
=> Fix warnings and CI failure

.run-gha-tests.sh, lib/rsync_store.ml, lib/rsync_store.mli, lib/store_spec.ml, main.ml, stress.sh, stress/stress.ml
Please note that I have **NO** idea what I'm doing: I'm working under the assumption that files are never modified in place in the store but always copied elsewhere first. If that ain't the case, well, please ignore and close this PR harshly!
I was hoping to save a bit of disk space in the obuilder store when using rsync:
```shell
/obuilder/store/result/ $ du -sh
2.1G	3438610c272ea59ea6c9b0cb93557cc430009e63f3d89d85416af6889fb94150
2.1G	ce0813553200cf888b0efa0cb2b2421dba8aaf4ba2c898d1a7dffc4483700ebd
```
Here `ce0813` was created from `343861` by running `sudo ln -f /usr/bin/opam-2.0 /usr/bin/opam`. As a full build involves a dozen steps, the copy-everything is eating my disk alive...  But by asking nicely, rsync could observe that files from `ce0813` are identical to those in `343861` …
=> Rsync hard-links to save space

lib/obuilder.ml
This is required or users of the library won't be able to create/configure a rsync store.
Probably an oversight from #102?
=> Expose `Rsync_store` module

.gitattributes, .github/workflows/main.yml, .run-gha-tests.sh
> The GH Actions test runs out of disk space, need to split that into smaller tests or cleanup disk space during the test.
_Originally posted by @tmcgilchrist in https://github.com/ocurrent/obuilder/issues/122#issuecomment-1273962129_
I hope this might help, it cleans after each store test. I would be also super nice if someone new how to cache the ppa and zfs install.
=> Split GHA tests and teardown local state

.github/workflows/main.yml, .run-gha-tests.sh
This action helps by caching the additional packages we need (btrfs and zfs utils). Downloading and installing them usually takes ~5 mins, I hope we can shave off some time.
=> GHA: cache apt packages

lib/btrfs_store.ml, lib/rsync_store.ml, lib/s.ml, lib/store_spec.ml, lib/zfs_store.ml, test/mock_store.ml
This allows configuring the OBuilder store fully inside the library and not using the store spec externally. I could add an interface to limit the exposed functions to the type and the cmdliner term.
=> Expose store root and cmdliner term with non-required store

.gitattributes, README.md, example.windows.spec, lib/btrfs_store.ml, lib/rsync_store.ml, lib/sandbox.runc.ml, lib/tar_transfer.ml, lib/zfs_store.ml, lib_spec/docker.ml, lib_spec/docker.mli, lib_spec/spec.ml, lib_spec/spec.mli, main.ml, stress/stress.ml, test/test.ml
The commit setting `safe.directory` shall be removed when our base images start shipping with
- https://github.com/ocurrent/ocaml-dockerfile/pull/108
=> Add support for Docker/Windows spec

lib/build_log.ml
Sorry, I closed #90 by mistake.
On Windows, one cannot move a directory if it has files opened inside. A similar case occurs with ZFS. Ensure that all `Build_log` file descriptors are closed before promoting the temporary build directory and the log file it contains as definitive build result.
We can either ensure that all tailers have finished reading before closing the log file and moving the directory, or pause the tailers and resume reading from the moved log file.
I'm still ~struggling~ working on it, it's not easy, I think I always end up in some sort of deadlock where the tailers and the `Db_store` layer are waiting on each other reciprocally.
There's just a little refactoring before my attempt (that I haven't pushed yet).
=> Refactor `Build_log` module

.github/workflows/main.yml, dune-project, example.spec, lib/build.ml, lib/config.ml, lib/dao.ml, lib/db.ml, lib/db_store.ml, lib/db_store.mli, lib/os.ml, lib/s.ml, lib/sandbox.runc.ml, main.ml, obuilder.opam, test/dummy.ml, test/dune, test/macos/dune, test/mock_exec.ml, test/test.ml
I've moved out of the big PR some little commits to ease review. I'll rebase the Windows PR when this one is merged.
=> Docker & Windows prerequisites

lib/sandbox.macos.ml
Typically this is either `/usr/local` or `/opt/homebrew`.
=> Added --fuse-path to allow selection of the path redirected by FUSE

.github/workflows/main.yml, .run-gha-tests.sh, README.md, lib/btrfs_store.ml, lib/build.ml, lib/db_store.ml, lib/db_store.mli, lib/macos.ml, lib/rsync_store.ml, lib/s.ml, lib/sandbox.macos.ml, lib/zfs_store.ml, lib_spec/docker.mli, lib_spec/spec.ml, stress.sh, stress/stress.ml, test/mock_exec.ml, test/mock_store.ml, test/test.ml
Porting tests require changing the root from `/` to `C:/`, the default shell to `cmd /S /C`, and mocking commands without `sudo`.
The store result need access to Docker, so as it requires an asynchronous call it has to be wrapped in a Lwt promise.
The log file has to be moved to a static location because of #118. There is still one test that fails, but it is difficult to debug.
Running tests has revealed that they might hang if an error occurs, and they won't necessarily reveal the error. Adding a fixed timeout of 10s helps by not letting the CI run for hours.
=> Windows prereqs tests

main.ml
It can be extended later to also clean other metadata.
This is useful for the Docker backend when I sometimes want to start over from a clean state, but I can't just delete the state directory since the images etc are stored in Docker. A possible extension would be to add functions to the store and sandbox to also clean their states (that will be needed for the Docker backend).
=> Add an `obuilder clean` command to clean all build results

lib/os.ml
In light of #148, let's remove unused code.
=> Remove unused `Os.copy`

test/test.ml
macOS doesn't have `sha256sum` but has `shasum -a 256`. The Docker backend isn't supported on macOS.
=> Skip test copy using `manifest.bash` on macOS

dune-project, lib/btrfs_store.ml, lib/build.ml, lib/dao.ml, lib/db_store.ml, lib/db_store.mli, lib/docker_store.ml, lib/dune, lib/os.ml, lib/rsync_store.ml, lib/s.ml, lib/zfs_store.ml, obuilder.opam, test/mock_store.ml
See discussion here https://github.com/ocurrent/ocluster/pull/229
=> Disk space and number of items in the store

lib/db_store.ml
When a new obuilder job is accepted by [ocurrent/ocluster](https://github.com/ocurrent/ocluster) the `build` function in [obuilder_build.ml](https://github.com/ocurrent/ocluster/blob/master/worker/obuilder_build.ml) is called.  This checks that there is enough free disk space possibly spawning an asynchronous thread `do_prune` to prune builds before running `Builder.build`.  `do_prune` invokes `Builder.prune` which calls `Store.prune` from `db_store.ml`.  The prune function queries the database to build a list of items ordered by the least recently used and begins deleting them.  The delete operation takes several minutes or longer, however the list of items was evaluated at the start.  It is possible that the build job which was started in parallel with `do_prune` or a subsequent job …
=> Prune one at a time up to the limit

lib/build.ml, lib/docker_sandbox.ml, lib/macos.ml, lib/os.ml, lib/s.ml, lib/sandbox.macos.ml, lib/sandbox.mli, lib/sandbox.runc.ml, lib/user_temp.ml, lib/zfs_store.ml, test/mock_sandbox.ml, test/mock_sandbox.mli
Rebase and squash of the current macOS worker.
=> macOS ZFS Sandbox

README.md, lib/build.ml, lib/build.mli, test/test.ml
The default shell used to run obuilder commands is currently `/bin/bash`. While this works under Linux and MacOS, this will fail under *BSD where bash, once installed, will be `/usr/local/bin/bash`.
This PR tries to make the location of `bash` flexible:
- the test framework will use `which bash` to get its proper path.
- commands spawned as `/bin/bash -c ...` are replaced with `/usr/bin/env bash -c ...` which will perform identically as long as a `bash` binary exists in the user's `PATH`.
This PR is necessary for the `manifest.bash` test to pass under FreeBSD.
=> Search for bash rather than assume it lies in /bin

doc/freebsd.ml, doc/index.mld, lib/archive_extract.ml, lib/archive_extract.mli, lib/dune, lib/obuilder.ml, lib/sandbox.jail.ml, lib/zfs_store.ml, main.ml
Jail-based sandbox implementation.
Related to https://github.com/ocurrent/obuilder/issues/109
=> FreeBSD sandbox module, using jail(8)

.github/workflows/main.sh, .github/workflows/main.yml, lib/obuilder.ml, lib/store_spec.ml, lib/xfs_store.ml, lib/xfs_store.mli
Format and mount an XFS volume like this:
apt install xfsprogs
mkfs.xfs -f -d agcount=64 -i maxpct=90 /dev/nvme0n1p1
mount -t xfs -o noatime /dev/nvme0n1p1 /var/cache/obuilder
`agcount` increases the number of _Allocation Groups_, which should increase the concurrent performance.  I have set this to the number of concurrent jobs the machine is servicing.  The rule of thumb seems to be file system size in GB / 4.  `maxpct` is the maximum percentage of the file system which can be used for inodes.  Many inodes are needed as each duplicated file needs an inode.
Run `ocluster-worker` with `--obuilder-store=xfs:/var/cache/obuilder`
The `result` directory can be inspected using `xfs_bmap -e -l -p -v -v -v <file>` to check that the file blocks are, in fact shared:
```
$ xfs_bmap -e -l -p -v -v …
```
=> XFS aka reflink store

lib/db_store.ml
When looking for cache results to be pruned, we execute this SQL query:
```
SELECT id FROM builds WHERE rc = 0 AND used < ? ORDER BY used ASC LIMIT ?
```
Here `rc` is the number of children a particular cache object has, and `used` is the timestamp of when that object was used.  As soon as the next cache object starts building, it becomes dependent on the parent, but we only update `rc` when the build has finished and the object is saved to the database.
There is a map `in_progress` which holds the current builds.  This PR adds a check to the prune function to query the `in_progress` operations to prevent the removal of these parents.
Depending upon the backend store, the delete operation may take a fraction of a second or many minutes; therefore, the query results are refreshed between …
=> Avoid pruning parent cache objects

lib/docker_sandbox.ml
`DisplayVersion` does not exist in Windows 2019 or earlier.  Check `CurrentBuild` instead.
In the `match` clause, I have listed all versions of Windows where a tag exists in the Microsoft registry.  The default value of `ltsc2022` should be ok until the next version of Windows Server.
References:
* https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
* https://mcr.microsoft.com/en-us/product/windows/servercore/tags
=> Check CurrentBuild instead of DisplayVersion

.github/workflows/main.sh, .github/workflows/main.yml, lib/os.ml, lib/overlayfs_store.ml, lib/overlayfs_store.mli, lib/store_spec.ml
The PR adds an OverlayFS backend to OBuilder.
OverlayFS is a union filesystem allowing a hierarchy of layers to be stacked on top of any other filesystem.  Notable this is useful as TmpFS can be used as the underlying filesystem with a x2 performance improvement over BTRFS on NMVe.
=> Overlayfs backend

dune-project, obuilder.opam
Corresponding to https://github.com/ocaml/opam-repository/pull/26331
=> Add upper bound on tar-unix 3

dune-project, example.spec, example.windows.spec, lib/archive_extract.ml, lib/btrfs_store.ml, lib/build_log.ml, lib/docker_store.ml, lib/os.ml, lib/overlayfs_store.ml, lib/rsync_store.ml, lib/xfs_store.ml, lib/zfs_store.ml, obuilder-spec.opam, obuilder.opam
Lwt's documentation reads:
> In most cases, it is better to use `failwith s` from the standard
> library.
and
> Whenever possible, it is recommended to use `raise exn` instead, as
> raise captures a backtrace, while `Lwt.fail` does not. If you call
> `raise exn` in a callback that is expected by Lwt to return a
> promise, Lwt will automatically wrap `exn` in a rejected promise,
> but the backtrace will have been recorded by the OCaml runtime.
>
> For example, `bind`'s second argument is a callback which returns a
> promise. And so it is recommended to use `raise` in the body of that
> callback.
>
> Use `Lwt.fail` only when you specifically want to create a rejected
> promise, to pass to another function, or store in a data structure.
Prefer to capture backtraces to improve debugability. …
=> Raise and reraise exceptions with Stdlib rather than Lwt

lib/os.ml
Looks like this was copied from Lwt at some point. It is not used within obuilder currently, nor have I found it used in any of our other projects. And it has since been exposed in Lwt. See https://github.com/ocsigen/lwt/blob/48abed72467ca7479e95f1be06d02f40c7c434bd/CHANGES#L25
=> Remove `delete_recursively`

lib/qemu_sandbox.ml, qemu/autounattend.xml.m4
Under Windows, we map access to download caches through NTFS junction points.  This effectively creates a file system directory which links to the cache drive.  However, we did not remove the junction points when the cache is not present.  During an `opam pin`, opam tries to create a folder under the `download-cache/git` directory (with no cache present).  The junction refers to a location which doesn't exist at this time and therefore the opam command fails.  This PR removes the junction when the cache is removed.
=> Fix pin on Windows

lib/os.ml
On Windows, "negative" exit codes are probably `NTSTATUS` values. For example, if a program accesses an invalid memory location, Unix sends a `SIGSEGV` signal which, if unhandled, will terminate the process (setting some kind of non-zero exit code - for example, Linux sets the exit code to 128 + signal number to give a fairly memorable 139). In the equivalent scenario, Windows throws an `EXCEPTION_ACCESS_VIOLATION` which, if handled by the default exception handler, will terminate the process with exit code `STATUS_ACCESS_VIOLATION`. These codes are large negative numbers, which are not terribly memorable in decimal, so for negative exit codes we instead display them in hexadecimal as `0xc0000005` is slightly more memorable than `-1073741819`.
=> Display Windows `NTSTATUS` exit codes in hex
